#Apartado de conexi\u00f3n a la base de datos
spring.application.name=AppSegurity
#URL de la base de datos
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/app_supervision}



# Configuracion de Correo Electronico (Spring Mail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo_de_prueba@gmail.com
spring.mail.password=tu_contrasena_de_aplicacion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

